{
 "title": "Pushgateway - VDBench",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "${VAR_JOB}" },
   { "name": "application", "query": "${VAR_APPLICATION}" },
   {
    "name": "instance",
    "label": "Gateway",
    "query": "label_values(up{job=\"$job\",application=\"$application\"}, instance)"
   },
   {
    "name": "exported_job",
    "label": "VDBench Job",
    "query": "label_values(cpu_total{job=\"$job\",instance=\"$instance\",application=\"$application\"},exported_job)"
   }
  ]
 },
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_total{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Sys + User"
    },
    {
     "expr": "cpu_sys{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Sys"
    }
   ]
  },
  { "title": "Raw I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "io_rate{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "title": "Througput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "mb_ps{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Bandwidth"
    }
   ]
  },
  {
   "title": "I/O Character",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "read_pct{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Read Percent"
    },
    {
     "expr": "bytes{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "I/O Size"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "q_depth{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Queue"
    }
   ]
  },
  {
   "title": "Latency Avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "read_resp{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "write_resp{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Latency Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "read_max{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "write_max{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Latency Overall",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "ms", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "resp_time{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Overall"
    },
    {
     "expr": "resp_stddev{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "STD"
    }
   ]
  },
  { "title": "File System I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Requested Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "reqps", "label": "Ops/Sec" }
   ],
   "targets": [
    {
     "expr": "req_std_ops_rate{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Ops"
    },
    {
     "expr": "req_std_ops_resp{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Response"
    }
   ]
  },
  {
   "title": "I/O Character",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "read_pct{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Read Percent"
    },
    {
     "expr": "xfer_size{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "I/O Size"
    }
   ]
  },
  {
   "title": "Read Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "reqps", "label": "Ops/Sec" }
   ],
   "targets": [
    {
     "expr": "read_rate{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Ops"
    },
    {
     "expr": "read_resp{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Response"
    }
   ]
  },
  {
   "title": "Write Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "reqps", "label": "Ops/Sec" }
   ],
   "targets": [
    {
     "expr": "write_rate{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Ops"
    },
    {
     "expr": "write_resp{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Response"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "MBs", "label": "Read/Wriite" }
   ],
   "targets": [
    {
     "expr": "read_mb_ps{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "write_mb_ps{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "total_mb_ps{job=\"$job\",instance=\"$instance\",application=\"$application\",exported_job=\"$exported_job\"}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}