global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'pushgateway'
    static_configs:
    - targets:
      - 192.168.56.161:9091
      labels:
        application: vdbench

